function w2mhsAssessor(workdir, pmap)
%w2mhsAssessor  Creates XNAT assessor for w2mhs pipeline
%
%   Syntax: w2mhsAssessor(pmap)
%
%   Inputs:
%       workdir     - Build path XNAT
%       pmap        - Path to the probability map generated by W2MHS.

%   Author: Nicolas Vinuesa
%   GIN, UMR 5296 - www.gin.cnrs.fr
%   Date: 01/07/2015, Rev.: 1b

im = load_untouch_nii(pmap);
voxdim = im.hdr.dime.pixdim(2:4);
voxdim = voxdim(1) * voxdim(2) * voxdim(3);

p040 = nnz(im.img(im.img>0.40)) * voxdim;
p045 = nnz(im.img(im.img>0.45)) * voxdim;
p050 = nnz(im.img(im.img>0.50)) * voxdim;
p055 = nnz(im.img(im.img>0.55)) * voxdim;
p060 = nnz(im.img(im.img>0.60)) * voxdim;
p065 = nnz(im.img(im.img>0.65)) * voxdim;
p070 = nnz(im.img(im.img>0.70)) * voxdim;
p075 = nnz(im.img(im.img>0.75)) * voxdim;
p080 = nnz(im.img(im.img>0.80)) * voxdim;
p085 = nnz(im.img(im.img>0.85)) * voxdim;
p090 = nnz(im.img(im.img>0.90)) * voxdim;

fid = fopen(strcat(workdir,'/vol.xml'),'w');
fprintf(fid,'<w2mhs:w2mhsAssessorData xmlns:xnat="http://nrg.wustl.edu/xnat" xmlns:w2mhs="http://nrg.wustl.edu/w2mhs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n');
fprintf(fid,'\t<w2mhs:buildPath>%s</w2mhs:buildPath>\n',workdir);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_040>%.2f</w2mhs:WMH_Volume_probability_map_thr_040>\n',p040);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_045>%.2f</w2mhs:WMH_Volume_probability_map_thr_045>\n',p045);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_050>%.2f</w2mhs:WMH_Volume_probability_map_thr_050>\n',p050);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_055>%.2f</w2mhs:WMH_Volume_probability_map_thr_055>\n',p055);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_060>%.2f</w2mhs:WMH_Volume_probability_map_thr_060>\n',p060);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_065>%.2f</w2mhs:WMH_Volume_probability_map_thr_065>\n',p065);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_070>%.2f</w2mhs:WMH_Volume_probability_map_thr_070>\n',p070);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_075>%.2f</w2mhs:WMH_Volume_probability_map_thr_075>\n',p075);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_080>%.2f</w2mhs:WMH_Volume_probability_map_thr_080>\n',p080);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_085>%.2f</w2mhs:WMH_Volume_probability_map_thr_085>\n',p085);
fprintf(fid,'\t<w2mhs:WMH_Volume_probability_map_thr_090>%.2f</w2mhs:WMH_Volume_probability_map_thr_090>\n',p090);
fprintf(fid,'</w2mhs:w2mhsAssessorData>');
fclose(fid);















